/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package fanisapp;


import ui.IConsole;

public class App {
    public static void main(String[] args) {
        //IConsole console = new Console();
        //ICommand command = new CommandImpl(""); // Create an instance of the command
        //console.setCommand(command); // Set the command for the console
        //console.run();
    }
}

